### ISSUE TITLE
is stop at this node,Maybe I need to pay for him?

### ISSUE THREAD

**Issue by nftlaolong** [choey/Comfy-Topaz#2] opened 2024-04-19 02:30 UTC
![screenshot-20240418-155740](https://github.com/choey/Comfy-Topaz/assets/112178483/fcbabace-fd88-44a8-a3f0-2b8fd3de92c3)

**Comment by choey** [comment] 2024-04-19 03:11
Dupe of #2.

**Closed by choey** 2024-04-19 03:11 UTC
